# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Bay Jekyll Theme
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/personal-site" # the subpath of the site
url: "anng217.github.io/personal-site" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: amnguyen5@wisc.edu
      link: mailto:amnguyen5@wisc.edu
  follow:
    - name: Twitter
      link: http://twitter.com/anng217
      username: "@anng217"
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    #- name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/anng217
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
